language: java

jdk:
- oraclejdk8

cache:
    directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.5

before_install:
 - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

